---
title: "jspar-intro"
author: "written by jspar project"
date: "`r Sys.Date()`"
tutorial:
  id: "researchwithr.ga"
  version: 0.5
output: 
  learnr::tutorial:
    includes: 
      in_header: header.html
      progressive: false
      language:
        en:
          text:
            startover: リセットする
          button:
            runcode: コードを実行
            continue: 続ける
            copyclipboard: クリップボードにコピー
            startover: 最初から
            previoustopic: 前のトピック
            nexttopic: 次のトピック
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)
library(learnr)

tutorial_options(exercise.timelimit = 10)
```

# 趣旨
研究データは普段Excelで扱ってるけども、コピペミスやら数式ミスやらで頭を抱えたことは無いでしょうか。

また、Rというとっつきにくいけど便利なツールがあるらしいと聞いたけども、やっぱりとっつきにくくて使えていない方もいるかも知れません。

そこでこのページでは、RとRのtidyverseパッケージの便利な関数を、実例とともに紹介します。

研究の効率化を少しでもお助けできれば幸いです。

## コンテンツリスト
- [dplyrを使ったデータ処理](https://researchwitr.ga/dplyr-intro)

今後少しずつコンテンツを増やしていきたいと考えています。


## 想定する対象

## 前準備

```{r, eval=FALSE}
library(tidyverse)
```

## pipe

## help

## shiny-test
```{r eruptions, echo=FALSE}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)
plotOutput("distPlot")
```

```{r, context="server"}
output$distPlot <- renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```
